# El loader debe ser javafml para que reconozca clases de Java
modLoader="javafml"
# Esta es la versión del cargador que pedía el error (4 o superior)
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="protectormod"
version="1.1.2"
displayName="Protection Mod"
authors="Shadow_K3"
description='''
Mod de protección de áreas.
'''
# Verifica que ProtectorMod termine en 'd' minúscula
modConstructor="com.tumod.protectormod.ProtectorMod"

[[dependencies.protectormod]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.protectormod]]
modId="minecraft"
type="required"
versionRange="[1.21,]"
ordering="NONE"
side="BOTH"